namespace DotNet.SystemCollections.Analyzers.OldStyleCollections
{
    using System.Collections.Immutable;
    using DotNet.SystemCollections.Analyzers.Helpers;
    using DotNet.SystemCollections.Analyzers.Helpers.Collections;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.Diagnostics;

    /// <summary>
    ///     This is used to analyze and detect for situations where fields are using "Old-Style" collections (i.e. collections from System.Collections).
    /// </summary>
    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    public class DoNotHaveFieldOfOldStyleCollectionTypeAnalyzer : DiagnosticAnalyzer
    {
        /// <summary>
        ///     This is the complete diagnostic ID for this analyzer.
        /// </summary>
        public static readonly string DiagnosticId = AnalyzerHelper.GetCompleteAnalyzerId(IdNumber);

        /// <summary>
        ///     The message format to use for diagnostics generated by this analyzer.
        /// </summary>
        internal const string MessageFormat = "The {0} field has a type ({1}) of an \"Old-Style\" collection (i.e. collection class from System.Collections).";

        /// <summary>
        ///     The description to use for diagnostics generated by this analyzer.
        /// </summary>
        private const string Description = "This is when a field is an \"Old-Style\" collection (i.e. a collection class from System.Collections).";

        /// <summary>
        ///     The category to use for diagnostics generated by this analyzer.
        /// </summary>
        private const string Category = "Old-Style Collections";

        /// <summary>
        ///     The number portion of the analyzer's <see cref="DiagnosticId"/>.
        /// </summary>
        private const int IdNumber = 1005;

#pragma warning disable RS1017 // DiagnosticId for analyzers must be a non-null constant.
        internal static DiagnosticDescriptor Rule = new DiagnosticDescriptor(DiagnosticId, AnalyzerHelper.AnalyzerTitle, MessageFormat, Category, DiagnosticSeverity.Warning, true, Description);
#pragma warning restore RS1017 // DiagnosticId for analyzers must be a non-null constant.

        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(Rule);

        public override void Initialize(AnalysisContext context)
        {
            context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.Analyze | GeneratedCodeAnalysisFlags.ReportDiagnostics);
            context.EnableConcurrentExecution();
            context.RegisterSymbolAction(AnalyzeSymbol, SymbolKind.Field);
        }

        private static void AnalyzeSymbol(SymbolAnalysisContext context)
        {
            // Cast down to a IFieldSymbol.
            IFieldSymbol fieldSymbol = (IFieldSymbol)context.Symbol;

            // Attempt to get the named type symbol associated with that field.
            INamedTypeSymbol fieldTypeSymbol = AnalyzerHelper.GetNamedTypeSymbol(fieldSymbol.Type);

            // If it was not possible to get the named type symbol.
            if (fieldTypeSymbol == null)
            {
                // Nothing more needs to be done here; just return.
                return;
            }

            // If the field's type is an old-style Collection class (i.e. class from System.Collections).
            if (CollectionHelper.IsOldStyleCollectionClass(fieldTypeSymbol))
            {
                // For every location where the field is defined.
                foreach (var location in fieldSymbol.Locations)
                {
                    // Report a diagnostic that "Old-Style" collections should not be used anymore.
                    context.ReportDiagnostic(Diagnostic.Create(Rule, location, fieldSymbol.Name, fieldTypeSymbol.GetFullNameWithoutPrefix()));
                }
            }
        }
    }
}
