name: Code validation for

on:
  push:
    branches: 
    - master
    - release/*
  workflow_dispatch:
  
jobs:
  build:
    name: Code Validation -> Build and test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build -c release
    - name: Test
      run: dotnet test -c release --no-build --verbosity normal
